[build-system]
requires = [
  # Essentials
  "setuptools <= 62.6.0; python_version < '3.12'",
  "setuptools; python_version >= '3.12'",

  # Plugins
  "setuptools-scm[toml]==8.3.1",
  "setuptools-scm-git-archive >= 1.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "jaxl/api/client/_scm_version.py"
